_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
architecture:
    value: resnet18
dataset:
    value: heat_equation_custom_solution
learning_rate:
    value: 0.01
